services:
  app:
    image: ghcr.io/sandemoit/algo-apriori:latest
    container_name: apriori_dev
    env_file:
      - stack.env
    expose:
      - "8080"
    restart: unless-stopped
    networks:
      - sandemo-network

networks:
  sandemo-network:
    external: true